services:
  db:
    image: mysql:8.0.45
    container_name: mysql_container
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - mysql_volume:/var/lib/mysql
    networks:
      - spring_docker_amqp

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitq_container
    hostname: rabbitq_container
    ports:
      - "5673:5672"
      - "15673:15672"
    networks:
      - spring_docker_amqp

  gestione-ordini:
    image: haukeys/gestione_ordini:0.0.2
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gestione-ordini
    ports:
      - "8082:8080"
    environment:
      - PORT=8080
      - MYSQL_URL=jdbc:mysql://mysql_container:3306/gestione_ordini
      - MYSQL_USERNAME=${MYSQL_USERNAME}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - SERVLET_CONTEXT_PATH=/api
      - API_DOCS_PATH=/v3/api-docs
      - PAYMENT_SERVICE_URL=http://gestione-pagamento:8080/api
      - RABBITMQ_HOST=rabbitq_container
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=guest
      - RABBITMQ_PASSWORD=guest
    depends_on:
      - db
      - rabbitmq
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/ordini/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - spring_docker_amqp

  gestione-pagamento:
    build:
      context: ../gestione_pagamento
      dockerfile: Dockerfile
    image: haukeys/gestione_pagamento:0.0.2
    container_name: gestione-pagamento
    ports:
      - "8081:8080"
    environment:
      - PORT=8080
      - MYSQL_URL=jdbc:mysql://mysql_container:3306/gestione_pagamento
      - MYSQL_USERNAME=${MYSQL_USERNAME}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - SERVLET_CONTEXT_PATH=/api
      - API_DOCS_PATH=/v3/api-docs
      - RABBITMQ_HOST=rabbitq_container
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=guest
      - RABBITMQ_PASSWORD=guest
      - CRON_CLEAN_PAYMENTS_RATE=300000
    depends_on:
      - db
      - rabbitmq
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/pagamenti/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - spring_docker_amqp
  gateway:
    build:
      context: ../gateway_ordini_pagamento
      dockerfile: Dockerfile
    image: haukeys/gateway_ordini_pagamento:0.0.1
    container_name: gateway-ordini-pagamento
    ports:
      - "8080:8080"
    depends_on:
      gestione-ordini:
          condition: service_healthy
      gestione-pagamento:
          condition: service_healthy
    networks:
      - spring_docker_amqp

networks:
  spring_docker_amqp:

volumes:
  mysql_volume:
    external: true
    name: mysql_volume





