services:
  db:
    image: mysql:8.0.45
    container_name: mysql_container
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - mysql_volume:/var/lib/mysql
    networks:
      - spring_docker_amqp

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq_container
    hostname: rabbitmq_container
    ports:
      - "5673:5672"
      - "15673:15672"
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "-q", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - spring_docker_amqp

  gestione-auth:
    build:
      context: ../gestione_ordini_auth
      dockerfile: Dockerfile
    image: haukeys/gestione_ordini_auth:0.0.3
    container_name: gestione-auth
    ports:
      - "8083:8080" # Port externe 8083 pour éviter les conflits avec ordini (8082) et pagamento (8081)
    environment:
      - PORT=8080
      - MYSQL_URL_AUTH=${MYSQL_URL_AUTH}
      - MYSQL_USERNAME=${MYSQL_USERNAME}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - SERVLET_CONTEXT_PATH=/api
      - API_DOCS_PATH=/v3/api-docs
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - JWT_EXPIRATION_TIME=${JWT_EXPIRATION_TIME}
    depends_on:
      - db
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/auth/health"] # À condition d'avoir un endpoint de health
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - spring_docker_amqp

  gestione-ordini:
    image: haukeys/gestione_ordini:0.0.3
    build:
      context: ../gestione_ordini
      dockerfile: Dockerfile
    container_name: gestione-ordini
    ports:
      - "8082:8080"
    environment:
      - PORT=8080
      - MYSQL_URL=${MYSQL_URL}
      - MYSQL_USERNAME=${MYSQL_USERNAME}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - SERVLET_CONTEXT_PATH=/api
      - API_DOCS_PATH=/v3/api-docs
      - RABBITMQ_HOST=${RABBITMQ_HOST}
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=${RABBITMQ_USERNAME}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
      - PAYMENT_SERVICE_URL=http://gestione-pagamento:8080/api
    depends_on:
      - db
      - rabbitmq
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/ordini/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - shared_logs:/app/logs #ajout d un volume pour garder une trace des log (/app/logs represente l equivalent de./log dans le ficher logback pour que les chemin soit les meme)
    networks:
      - spring_docker_amqp

  gestione-pagamento:
    build:
      context: ../gestione_pagamento
      dockerfile: Dockerfile
    image: haukeys/gestione_pagamento:0.0.3
    container_name: gestione-pagamento
    ports:
      - "8081:8080"
    environment:
      - PORT=8080
      - MYSQL_URL_PAGAMENTO=${MYSQL_URL_PAGAMENTO} # reste en MYSQL_URL
      - MYSQL_USERNAME=${MYSQL_USERNAME}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - SERVLET_CONTEXT_PATH=/api
      - API_DOCS_PATH=/v3/api-docs
      - RABBITMQ_HOST=${RABBITMQ_HOST}
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=${RABBITMQ_USERNAME}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
      - CRON_CLEAN_PAYMENTS_RATE=${CRON_CLEAN_PAYMENTS_RATE}
      - AUTH_SERVICE_URL=${AUTH_SERVICE_URL}
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_USERNAME=${SMTP_USERNAME}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
    depends_on:
      - db
      - rabbitmq
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/pagamenti/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - shared_logs:/app/logs #ajout d un volume pour garder une trace des log (/app/logs represente l equivalent de./log dans le ficher logback pour que les chemin soit les meme)
    networks:
      - spring_docker_amqp

  gateway:
    build:
      context: ../gateway_ordini_pagamento
      dockerfile: Dockerfile
    image: haukeys/gateway_ordini_pagamento:0.0.3
    container_name: gateway-ordini-pagamento
    ports:
      - "8080:8080"
    environment:
      - GATEWAY_PORT=8080
      - GESTIONE_AUTH_HOST=gestione-auth
      - GESTIONE_AUTH_PORT=8080
      - PATH_AUTH=api/auth
      - GESTIONE_ORDINI_HOST=gestione-ordini
      - GESTIONE_ORDINI_PORT=8080
      - PATH_ORDINI=api/ordini
      - GESTIONE_PAGAMENTO_HOST=gestione-pagamento
      - GESTIONE_PAGAMENTO_PORT=8080
      - PATH_PAGAMENTO=api/pagamenti
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - JWT_EXPIRATION_TIME=${JWT_EXPIRATION_TIME}

    networks:
      - spring_docker_amqp
    # --- CONFIGURATION STACK MONITORING LOKI / ALLOY / GRAFANA ---

  loki:
    image: grafana/loki:3.0.0
    container_name: monitoring-loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - spring_docker_amqp

  alloy:
    image: grafana/alloy:v1.1.1
    container_name: monitoring-alloy
    user: "root"
    volumes:
      - ./alloy/config.alloy:/etc/alloy/config.alloy
      - shared_logs:/var/log/apps:ro
    entrypoint:
      - /usr/bin/alloy
      - run
      - --storage.path=/var/lib/alloy/data
      - /etc/alloy/config.alloy
    ports:
      - "12345:12345"
    depends_on:
      - loki
    networks:
      - spring_docker_amqp

  grafana:
    image: grafana/grafana:11.0.0
    container_name: monitoring-grafana
    ports:
      - "3002:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
    depends_on:
      - loki
    networks:
      - spring_docker_amqp
networks:
  spring_docker_amqp:

volumes:
  mysql_volume:
    external: true
    name: mysql_volume
  shared_logs:
    external: true
    name: shared_logs

#dans notre cas avec logback les fichiers log de pagamento seron dans un ".log" qui existe dans le docker et sera effacer à chaque lancement.


