spring.application.name=gestione_ordini

#db
spring.datasource.url = ${MYSQL_URL}
spring.datasource.username=${MYSQL_USERNAME}
spring.datasource.password=${MYSQL_PASSWORD}


#jpa
spring.jpa.hibernate.ddl-auto=update
server.servlet.context-path=${SERVLET_CONTEXT_PATH}


#swagger
springdoc.api-docs.path=${API_DOCS_PATH}

#microservice
payment.service.url=${PAYMENT_SERVICE_URL}

# Si ce service utilise la même BDD ou une autre sur le port 3307

# Connexion au même RabbitMQ
spring.rabbitmq.host=${RABBITMQ_HOST}
spring.rabbitmq.port=${RABBITMQ_PORT}
spring.rabbitmq.username=${RABBITMQ_USERNAME}
spring.rabbitmq.password=${RABBITMQ_PASSWORD}